from sqlalchemy import Column, Integer, String, JSON, ForeignKey, Boolean
from sqlalchemy.orm import relationship

from backend.core.database import Base


class Word(Base):
    __tablename__ = "words"

    id = Column(Integer, primary_key=True)
    english = Column(String, nullable=False, unique=True, index=True)
    transcription = Column(String)
    part_of_speech = Column(String)
    translations = Column(JSON)
    frequency_rank = Column(Integer)
    cefr_level = Column(String)

    # Categorization for function words
    word_category = Column(String, default="regular")  # "regular", "function", "preposition"
    grammar_notes = Column(JSON)  # For function words like "the", "a", "to"

    # Extended linguistic data (generated by AI)
    verb_forms = Column(JSON)  # {"past": "went", "past_participle": "gone", "present_participle": "going"}
    collocations = Column(JSON)  # ["make a decision", "make sense", "make progress"]
    phrasal_verbs = Column(JSON)  # [{"phrase": "look for", "meaning": "искать"}, ...]
    usage_notes = Column(JSON)  # ["often used with 'the'", "countable/uncountable", ...]
    ai_enriched = Column(Integer, default=0)  # 1 if AI enrichment done

    contexts = relationship(
        "WordContext", back_populates="word", cascade="all,delete"
    )

    def __repr__(self) -> str:
        return f"<Word id={self.id} english='{self.english}'>"


class WordContext(Base):
    __tablename__ = "word_contexts"

    id = Column(Integer, primary_key=True)
    word_id = Column(Integer, ForeignKey("words.id"), nullable=False)
    sentence_en = Column(String, nullable=False)
    sentence_ru = Column(String)
    source = Column(String)
    difficulty = Column(Integer, default=1)

    word = relationship("Word", back_populates="contexts")

    def __repr__(self) -> str:
        return f"<WordContext id={self.id} word_id={self.word_id}>"


class PhrasalVerb(Base):
    """Phrasal verbs like 'look up', 'give in', 'turn out'."""

    __tablename__ = "phrasal_verbs"

    id = Column(Integer, primary_key=True)
    phrase = Column(String, nullable=False, unique=True, index=True)  # "look up"
    base_verb = Column(String, index=True)  # "look"
    particle = Column(String)  # "up"
    translations = Column(JSON)  # ["искать", "смотреть вверх"]
    definitions = Column(JSON)  # [{"en": "to search for", "ru": "искать"}]
    frequency_rank = Column(Integer)
    cefr_level = Column(String)
    is_separable = Column(Boolean, default=True)  # "look IT up" vs "look up IT"

    contexts = relationship(
        "PhrasalVerbContext", back_populates="phrasal_verb", cascade="all,delete"
    )

    def __repr__(self) -> str:
        return f"<PhrasalVerb id={self.id} phrase='{self.phrase}'>"


class PhrasalVerbContext(Base):
    """Example sentences for phrasal verbs."""

    __tablename__ = "phrasal_verb_contexts"

    id = Column(Integer, primary_key=True)
    phrasal_verb_id = Column(Integer, ForeignKey("phrasal_verbs.id"), nullable=False)
    sentence_en = Column(String, nullable=False)
    sentence_ru = Column(String)
    source = Column(String)  # "seed", "tatoeba", "ai"
    difficulty = Column(Integer, default=1)

    phrasal_verb = relationship("PhrasalVerb", back_populates="contexts")

    def __repr__(self) -> str:
        return f"<PhrasalVerbContext id={self.id} phrasal_verb_id={self.phrasal_verb_id}>"


class IrregularVerb(Base):
    """Irregular verbs with their three forms."""

    __tablename__ = "irregular_verbs"

    id = Column(Integer, primary_key=True)
    base_form = Column(String, nullable=False, unique=True, index=True)  # "go"
    past_simple = Column(String, nullable=False)  # "went"
    past_participle = Column(String, nullable=False)  # "gone"
    translations = Column(JSON)  # ["идти", "ехать"]
    transcription_base = Column(String)  # /ɡoʊ/
    transcription_past = Column(String)  # /wɛnt/
    transcription_participle = Column(String)  # /ɡɒn/
    frequency_rank = Column(Integer)
    cefr_level = Column(String)
    verb_pattern = Column(String)  # "ABC" (go-went-gone), "ABB" (buy-bought-bought), "AAA" (cut-cut-cut)

    contexts = relationship(
        "IrregularVerbContext", back_populates="irregular_verb", cascade="all,delete"
    )

    def __repr__(self) -> str:
        return f"<IrregularVerb id={self.id} base_form='{self.base_form}'>"


class IrregularVerbContext(Base):
    """Example sentences for irregular verbs."""

    __tablename__ = "irregular_verb_contexts"

    id = Column(Integer, primary_key=True)
    irregular_verb_id = Column(Integer, ForeignKey("irregular_verbs.id"), nullable=False)
    sentence_en = Column(String, nullable=False)
    sentence_ru = Column(String)
    verb_form_used = Column(String)  # "base", "past", "participle"
    source = Column(String)  # "seed", "tatoeba", "ai"
    difficulty = Column(Integer, default=1)

    irregular_verb = relationship("IrregularVerb", back_populates="contexts")

    def __repr__(self) -> str:
        return f"<IrregularVerbContext id={self.id} irregular_verb_id={self.irregular_verb_id}>"
